update more apps, add Thorium
blueOkiris/aip-man-pkg-list pull request #3
Opened 2023-03-06 12:11 UTC by Drsheppard01

2023-03-06 17:04 UTC, blueOkiris requested changes
Other than the continuous thing for appimagetool, the rest looks good.

I will note a couple of these like LibreOffice may get new downloads before the version is increased to match, but that shouldn't cause any problems with upgrades. Just some people would potentially have a newer version than they thought they downloaded until the package list is corrected, so that's fine.

2023-03-10 09:06 UTC, Drsheppard01 commented on pkgs.json
> +        "version": "Continuous",
I think that entering an internal number and occasionally updating the assembly and the number assigned would be more convenient.

2023-03-10 15:23 UTC, blueOkiris commented on pkgs.json
> +        "version": "Continuous",
They just released a new version (I'm watching it, apparently), so I uploaded that [here](https://github.com/blueOkiris/aip-man-pkgs/releases/download/appimagetool-2023.3.10.1)

You can use version "2023.3.10.1" and link here "https://github.com/blueOkiris/aip-man-pkgs/releases/download/appimagetool-2023.3.10.1/appimagetool-x86_64.AppImage"

Might be good to keep version 13 as "appimagetool-stable" or something as well though.

2023-04-03 04:27 UTC, blueOkiris commented
I haven't seen any progress made, so I went ahead and updated the apps that were changed in this PR, and I'm closing this.

Here's the [monthly updates PR](https://github.com/blueOkiris/aip-man-pkg-list/pull/4)

If you have more changes feel free to open a new PR

2023-04-03 04:27 UTC, closed without merging

2023-04-03 06:08 UTC, Drsheppard01 commented
Thanks, I've been a little busy, what 'bout the apps with the continous tag, I think it's better to release them with the tag which has format "continous-mm-dd-yyyy". This will help users to have the latest build with the latest commits, and aip-man will be able to parse the information and download the desired build

2023-04-03 06:27 UTC, blueOkiris commented
That works for me. Aip-man just needs something to reference when the build disappears, so simply marking continuous and date makes sense.

I'll add a PR tomorrow to rename the relevant apps