Update versions, delete abandoned, fix issues
blueOkiris/aip-man-pkg-list pull request #6
Opened 2023-04-11 22:57 UTC by Drsheppard01

2023-04-11 23:00 UTC, Drsheppard01 reviewed
zrythm now packaged only zip/flatpak

2023-04-12 06:08 UTC, blueOkiris requested changes
There's an extra line and a missing quote, but the rest looks good to me

2023-04-12 06:08 UTC, blueOkiris commented on pkgs.json
> +        "url": " https://cdn.filen.io/desktop/release/filen_x86_64.AppImage
I think you're missing an end `"` here

2023-04-12 06:08 UTC, blueOkiris commented on pkgs.json
> +
Can you delete this extra line?

2023-04-12 13:42 UTC, Drsheppard01 commented on pkgs.json
> +        "url": " https://cdn.filen.io/desktop/release/filen_x86_64.AppImage
yep, i fix this later

2023-04-12 20:28 UTC, blueOkiris approved these changes

2023-04-12 20:28 UTC, merged