add more apps
blueOkiris/aip-man-pkg-list pull request #7
Opened 2023-04-13 15:10 UTC by Drsheppard01

2023-04-20 01:31 UTC, blueOkiris requested changes
It's mostly good, but I have one nitpick.

I'd like package names to be consistent and match what people expect of a package manager which is typically:
- Lowercase
- Hyphenated instead of underscored
- No special characters

You've added quite a few with PascalCase, and I'd like them to match the existing package-names. I tried to mark all of them, so it's easier for you to find.

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Chiaki",
Lowercase please.

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "digiKam",
Lower case

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "DuckStation",
Lowercase. `duckstation` or `duck-station` works.

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Beekeeper-Studio",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "86Box",
Please keep package names lower case for consistency, so `86box` or `86-box`
Afterall, it's not the name of the app itself, but just what aip-man uses when doing `install` and such.

It's pretty standard to do lowercase for package names in package managers, and while aip-man could've been different, most of the other packages are already lowercase.

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "ArmCord",
Lowercase to `armcord` or `arm-cord` please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Frappe-Books",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "GitHubDesktop",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "KeePassXC",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "GameHub",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Kuro",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "LeoCAD",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "LibreCAD",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "LibreOffice-fresh-basic",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Login_Manager_Settings",
Lowercase please, and use hyphen over underscore, so `login-manager-settings`

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Mochi",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "MQTTX",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "MyPaint",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "ownCloud",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "PhotoQt",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Play!",
Lowercase please and no ! (people would have to escape it to install)

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "QElectrotech",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "QOwnNotes",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "qView",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Rare",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "RawTherapee",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "RPCS3",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "SMPlayer",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Storyboarder",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Syncplay",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Tropy",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Vieb",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "WebCord",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Whalebird",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Zettlr",
Lowercase please

2023-04-20 01:31 UTC, blueOkiris commented on pkgs.json
> +        "name": "Zulip",
Lowercase please

2023-04-20 21:38 UTC, Drsheppard01 commented on pkgs.json
> +        "name": "Login_Manager_Settings",
renamed in gdm-settings and ordered

2023-04-21 03:37 UTC, blueOkiris requested changes

2023-04-21 03:37 UTC, blueOkiris commented on pkgs.json
> +        "name": "gitHubdesktop",
Missed one of the lowercases

2023-04-21 17:03 UTC, blueOkiris approved these changes
Looks good. Thanks for adding

2023-04-21 17:03 UTC, merged